name: Extract and Process TikTok Video IDs

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every day at 5 PM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-process-video-ids:
    runs-on: ubuntu-latest

    env:
      AWANLLM_API_KEY: ${{ secrets.AWANLLM_API_KEY }}
      TOK_API_KEY: ${{ secrets.TOK_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Ensure the token persists across actions
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the script to get unprocessed video IDs
      id: run-script
      run: |
        UNPROCESSED_VIDEO_IDS=$(python get_latest_video_ids.py)
        echo "UNPROCESSED_VIDEO_IDS=$UNPROCESSED_VIDEO_IDS" >> $GITHUB_ENV

    - name: Print unprocessed video IDs
      run: echo "${{ env.UNPROCESSED_VIDEO_IDS }}"

    - name: Process unprocessed video IDs
      run: |
        python process_videos.py "${{ env.UNPROCESSED_VIDEO_IDS }}"
      env:
        AWANLLM_API_KEY: ${{ secrets.AWANLLM_API_KEY }}
        TOK_API_KEY: ${{ secrets.TOK_API_KEY }}

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Commit and push changes
      run: |
        git add reviews.json processed_videos.json
        git commit -m "Update reviews and processed videos"
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin HEAD:main
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
