name: Extract and Process TikTok Video IDs

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 5 PM UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  fetch-and-process-video-ids:
    runs-on: ubuntu-latest

    env:
      AWANLLM_API_KEY: ${{ secrets.AWANLLM_API_KEY }}
      TOK_API_KEY: ${{ secrets.TOK_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the script to get unprocessed video IDs
      id: run-script
      run: |
        UNPROCESSED_VIDEO_IDS=$(python get_latest_video_ids.py)
        echo "UNPROCESSED_VIDEO_IDS=$UNPROCESSED_VIDEO_IDS" >> $GITHUB_ENV

    - name: Print unprocessed video IDs
      run: echo "${{ env.UNPROCESSED_VIDEO_IDS }}"

    - name: Process unprocessed video IDs
      run: |
        python process_videos.py "${{ env.UNPROCESSED_VIDEO_IDS }}"
      env:
        AWANLLM_API_KEY: ${{ secrets.AWANLLM_API_KEY }}
        TOK_API_KEY: ${{ secrets.TOK_API_KEY }}
